[package]
name = "td-types"
version = "0.1.0"
edition = "2021"

[features]
schema = ["dep:schemars"]

[dependencies]
serde = { version = "1", features = ["derive"] }
schemars = { version = "1", optional = true }
